site_name: Okdesk 文档
pages:
    - '简介': 'index.md'
    - 'Okdesk 是什么': 'whatisokdesk.md'
    - '网页集成': 'web.md'
    - 'iOS 集成': 'ios.md'
    - 'Android 集成': 'android.md'
    - '微信集成': 'wechat.md'
    - '微博集成': 'weibo.md'
